CREATE TABLE EMPLEADOS (
                        DAS VARCHAR (5) NOT NULL PRIMARY KEY,
                        PASSWORD VARCHAR (6) DEFAULT '0000' NOT NULL,
                        NOMBRE VARCHAR (20) NOT NULL,
                        APELLIDOS VARCHAR (50),
                        STATUS VARCHAR (1) NOT NULL,
                        ADMINISTRADOR VARCHAR (1) NOT NULL);

CREATE TABLE TAREAS (
                        ID_TAREA INT NOT NULL PRIMARY KEY,
                        NOMBRE VARCHAR (20) NOT NULL,
                        DESCRIPCION VARCHAR (100));

--Crear EMPLEADOS
INSERT INTO EMPLEADOS (DAS, PASSWORD, NOMBRE, APELLIDOS, STATUS, ADMINISTRADOR) VALUES ('PR005', DEFAULT, 'FELIPE', 'SIERRA', 'S', 'S');

--Modificar STATUS S/N de los EMPLEADOS
UPDATE EMPLEADOS SET STATUS='' WHERE DAS='';

--Modificar ADMINISTRADOR S/N de los EMPLEADOS
UPDATE EMPLEADOS SET ADMINISTRADOR='' WHERE DAS='';

--Modificar TODO de los EMPLEADOS
UPDATE EMPLEADOS SET DAS='', PASSWORD='', NOMBRE='', APELLIDOS='', STATUS='', ADMINISTRADOR='' WHERE DAS='';

--Consultar TODOS los EMPLEADOS
SELECT * FROM EMPLEADOS;

--Consultar TODOS los ADMINISTRADORES
SELECT * FROM EMPLEADOS WHERE ADMINISTRADOR='S';

--Consultar TODOS los USUARIOS
SELECT * FROM EMPLEADOS WHERE ADMINISTRADOR='N';

--Consultar TODOS los USUARIOS con ACCESO
SELECT * FROM EMPLEADOS WHERE ADMINISTRADOR='N' AND STATUS='S';

--Borrar usuarios por DAS
DELETE FROM EMPLEADOS WHERE DAS='';

--Borrar usuarios por NOMBRE y APELLIDOS
DELETE FROM EMPLEADOS WHERE NOMBRE='' AND APELLIDOS='';


--Crear TAREAS
INSERT INTO TAREAS (ID_TAREA, NOMBRE, DESCRIPCION) VALUES (0, '', '');

--Modificar TAREAS según su ID
UPDATE TAREAS SET NOMBRE='', DESCRIPCION='' WHERE ID_TAREAS=0;

--Modificar TAREAS según su NOMBRE
UPDATE TAREAS SET NOMBRE='', DESCRIPCION='' WHERE NOMBRE=0;

--Consultar TODAS las TARREAS
SELECT * FROM TAREAS;

--Consultar TAREAS según NOMBRE
SELECT * FROM TAREAS WHERE NOMBRE='';

--Borrar TAREAS según ID_TAREA
DELETE FROM TAREAS WHERE ID_TAREA=0;

--Borrar TAREAS según NOMBRE
DELETE FROM TAREAS WHERE NOMBRE='';
